# TODO: Merge with Navidrome, Feishin
# TIP: Use Nextcloud directory as download folder to easen file managment without having to ssh into the maching permanently

services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - $METUBE_PATH_DOWNLOADS:/downloads