services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ${PATH_VAULTWARDEN_DATA}:/data
    ports:
      - ${VAULTWARDEN_DOCKER_PORT}:80
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DEBIAN_FRONTEND=${DEBIAN_FRONTEND}
      - ROCKET_ADDRESS=${ROCKET_ADDRESS}
      - ROCKET_PORT=80
      - ROCKET_PROFILE=release
      # My yubikey stuff :)
      - YUBICO_CLIENT_ID=${YUBICO_CLIENT_ID}
      - YUBICO_SECRET_KEY=${YUBICO_SECRET_KEY}
      # OIDC
      - SSO_ENABLED=${SSO_ENABLED}
      - SSO_AUTHORITY=${SSO_AUTHORITY}
      - SSO_CLIENT_ID=${SSO_CLIENT_ID}
      - SSO_CLIENT_SECRET=${SSO_CLIENT_SECRET}
      - SSO_SCOPES=${SSO_SCOPES}
      - SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION=${SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION}
      - SSO_CLIENT_CACHE_EXPIRATION=${SSO_CLIENT_CACHE_EXPIRATION}
      - SSO_ONLY=${SSO_ONLY}
      - SSO_SIGNUPS_MATCH_EMAIL=${SSO_SIGNUPS_MATCH_EMAIL}